---
- name: "update and upgrade packages"
  become: yes
  apt:
    update_cache: yes
    upgrade: yes

- name: "install tar"
  become: yes
  apt:
    name: tar
    state: latest
    update_cache: yes

- name: "Install Node.js 13"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes
    
- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes

- name: "copy built backend files"
  become: yes
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: "Extract backend"
  shell: |
    cd /home/ubuntu
    tar -xzvf artifact.tar.gz
    
- name: "Start pm2"
  shell: |    
    npm i
    pm2 stop default
    pm2 start npm -- start
