---
- name: "update and upgrade packages"
  become: yes
  apt:
    update_cache: yes
    upgrade: yes

- name: "install tar"
  become: yes
  apt:
    name: tar
    state: latest
    update_cache: yes

- name: install nodejs 13.x
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash 
    sudo apt-get install -y nodejs

- name: "Install npm"
  become: true
  apt:
    name: npm
    state: latest
    update_cache: yes
    
- name: "Install PM2 Globally"
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes

- name: "copy built backend files"
  become: yes
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: "Extract backend"
  shell: |
    cd /home/ubuntu
    tar -xzvf artifact.tar.gz
    
- name: npm install and Start pm2
  shell: |    
    npm install
    pm2 stop default
    pm2 start npm -- start
